dubbo:
  application:
    name: demo-dubbo-consumer
  registries:
    todubbo:
      address: tsfconsul://localhost:8500
    tocloud:
      address: tocloudtsfconsul://localhost:8500
      default: false
server:
  port: 18081